# .github/workflows/build-and-push-public-ecr.yml

name: Build and Push to Public ECR

on:
  push:
    branches: [main]  # or your branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Public ECR region

    - name: Login to Public ECR
      run: |
        aws ecr-public get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin public.ecr.aws

    - name: Build and Push Docker Image to Public ECR
      run: |
        IMAGE_URI=public.ecr.aws/i5u5r0e0/stagging:latest
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
